// main.js - common frontend behaviour and server integration
(function(){
  const API = ''; // if hosted, put your server URL here, e.g. 'https://robibux-server.onrender.com'
    // To use server, set localStorage 'rbx_api_url' or replace API above

      function apiURL(path){
          const base = localStorage.getItem('rbx_api_url') || API;
              return base ? base + path : null;
                }

                  function getPoints(){ return parseInt(localStorage.getItem('rbx_points')||'0',10); }
                    function setPoints(v){ localStorage.setItem('rbx_points', String(v)); }

                      // update header names/avatar
                        document.addEventListener('DOMContentLoaded', async ()=>{
                            const id = localStorage.getItem('rbx_userId');
                                document.querySelectorAll('#miniName,#miniName2,#welcomeUser,#profileName,#profileId').forEach(el=>{
                                      if(!el) return;
                                            if(el.id === 'profileId') el.textContent = id || '—';
                                                  else el.textContent = id || 'Invité';
                                                      });
                                                          document.querySelectorAll('#miniAvatar,#miniAvatar2,#profileAvatarImg,#headerAvatar').forEach(img=>{
                                                                if(img) img.src = 'assets/images/default-avatar.png';
                                                                    });

                                                                        // try fetch live feed from server
                                                                            const url = apiURL('/api/live-feed');
                                                                                if(url){
                                                                                      try{
                                                                                              const resp = await fetch(url);
                                                                                                      if(resp.ok){
                                                                                                                const json = await resp.json();
                                                                                                                          renderLiveFeed(json.feed || []);
                                                                                                                                  } else console.warn('live-feed error', resp.status);
                                                                                                                                        } catch(e){ console.warn('live-feed fetch error', e); }
                                                                                                                                            } else {
                                                                                                                                                  // no server: create sample feed
                                                                                                                                                        const sample = [
                                                                                                                                                                { userId:'skycatgaming74', name:'skycatgaming74', avatar:'assets/images/default-avatar.png', amount: 34 },
                                                                                                                                                                        { userId:'ROBLOX2344710', name:'ROBLOX2344710', avatar:'assets/images/default-avatar.png', amount: 1 },
                                                                                                                                                                                { userId:'Pullu958', name:'Pullu958', avatar:'assets/images/default-avatar.png', amount: 1 }
                                                                                                                                                                                      ];
                                                                                                                                                                                            renderLiveFeed(sample);
                                                                                                                                                                                                }

                                                                                                                                                                                                    // set points
                                                                                                                                                                                                        const p = getPoints();
                                                                                                                                                                                                            document.getElementById('statPoints')?.innerText = p;
                                                                                                                                                                                                                document.getElementById('myPoints')?.innerText = p;
                                                                                                                                                                                                                    document.getElementById('profilePoints')?.innerText = p;
                                                                                                                                                                                                                        document.getElementById('withdrawAvailable')?.innerText = p;

                                                                                                                                                                                                                            // attach withdraw if present
                                                                                                                                                                                                                                document.getElementById('withdrawBtn')?.addEventListener('click', async ()=>{
                                                                                                                                                                                                                                      const amt = parseInt(document.getElementById('withdrawInput').value||'0',10);
                                                                                                                                                                                                                                            const result = document.getElementById('withdrawResult');
                                                                                                                                                                                                                                                  if(!amt || amt <=0){ result.textContent = 'Montant invalide'; return; }
                                                                                                                                                                                                                                                        let points = getPoints();
                                                                                                                                                                                                                                                              if(amt > points){ result.textContent = 'Pas assez de points'; return; }
                                                                                                                                                                                                                                                                    points -= amt; setPoints(points);
                                                                                                                                                                                                                                                                          // push to server history if possible
                                                                                                                                                                                                                                                                                const api = apiURL('/api/award');
                                                                                                                                                                                                                                                                                      if(api){
                                                                                                                                                                                                                                                                                              try{
                                                                                                                                                                                                                                                                                                        await fetch(api, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ userId: localStorage.getItem('rbx_userId'), amount: -amt, type: 'withdraw' })});
                                                                                                                                                                                                                                                                                                                } catch(e){ console.warn('award withdraw error', e); }
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                            result.textContent = `Retrait simulé : ${amt} points. Nouveau solde : ${points}`;
                                                                                                                                                                                                                                                                                                                                  // update displays
                                                                                                                                                                                                                                                                                                                                        document.getElementById('profilePoints')?.innerText = points;
                                                                                                                                                                                                                                                                                                                                              document.getElementById('myPoints')?.innerText = points;
                                                                                                                                                                                                                                                                                                                                                    document.getElementById('withdrawAvailable')?.innerText = points;
                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                            // profile history render
                                                                                                                                                                                                                                                                                                                                                                const histEl = document.getElementById('historyList');
                                                                                                                                                                                                                                                                                                                                                                    if(histEl){
                                                                                                                                                                                                                                                                                                                                                                          const hist = JSON.parse(localStorage.getItem('rbx_history')||'[]');
                                                                                                                                                                                                                                                                                                                                                                                if(hist.length === 0) histEl.innerHTML = '<li class="muted">Aucune action pour l\\'instant</li>';
                                                                                                                                                                                                                                                                                                                                                                                      else hist.forEach(h=>{
                                                                                                                                                                                                                                                                                                                                                                                              const li = document.createElement('li');
                                                                                                                                                                                                                                                                                                                                                                                                      li.textContent = `${h.type} ${h.amount||''} ${h.date ? ' — ' + (new Date(h.date).toLocaleString()) : ''}`;
                                                                                                                                                                                                                                                                                                                                                                                                              histEl.appendChild(li);
                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                            // render live feed (top bar)
                                                                                                                                                                                                                                                                                                                                                                                                                              function renderLiveFeed(feed){
                                                                                                                                                                                                                                                                                                                                                                                                                                  // feed: array of {userId, name, avatar, amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                      const target = document.getElementById('topBanner') || document.getElementById('liveTicker') || document.getElementById('liveFeed');
                                                                                                                                                                                                                                                                                                                                                                                                                                          if(!target) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                              target.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                  feed.forEach(item=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const el = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                              el.className = 'live-item';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    el.style.display = 'inline-flex';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          el.style.alignItems = 'center';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                el.style.gap = '8px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      el.style.padding = '6px 10px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            el.style.marginRight = '8px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  el.style.background = 'rgba(255,255,255,0.02)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        el.style.borderRadius = '8px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const img = document.createElement('img');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    img.src = item.avatar || 'assets/images/default-avatar.png';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          img.style.width = '36px'; img.style.height = '36px'; img.style.borderRadius = '50%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const name = document.createElement('div'); name.innerText = item.name || item.userId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const amount = document.createElement('div'); amount.innerText = (item.amount ? `+${item.amount} R$` : '—');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            amount.style.color = 'var(--neon-blue)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  el.appendChild(img); el.appendChild(name); el.appendChild(amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target.appendChild(el);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // simple auto-scroll effect for scroll-banner containers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(target.classList.contains('scroll-banner') || target.id === 'topBanner'){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let pos = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setInterval(()=> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(target.scrollWidth <= target.clientWidth) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pos += 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(pos > target.scrollWidth) pos = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target.scrollLeft = pos;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, 60);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // expose a helper to force award (for testing)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                window._awardLocal = async function(userId, amount){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const api = apiURL('/api/award');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(api){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const r = await fetch(api, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ userId, amount, type:'offer' })});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const j = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('award result', j);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // refresh live feed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const lf = apiURL('/api/live-feed');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(lf){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const resp = await fetch(lf); const data = await resp.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderLiveFeed(data.feed || []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch(e){ console.warn(e); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // local only
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const hist = JSON.parse(localStorage.getItem('rbx_history')||'[]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      hist.unshift({ type:'offer', amount, date: new Date().toISOString() });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            localStorage.setItem('rbx_history', JSON.stringify(hist));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  localStorage.setItem('rbx_points', String(getPoints()+amount));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('Points ajoutés localement: ' + amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })();